# Generated by Django 4.2.5 on 2024-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(null=True, upload_to='Media/Course_Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
