# Generated by Django 4.2.5 on 2024-07-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_courses_delete_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Courses_Upload',
        ),
    ]
