# Generated by Django 4.2.5 on 2024-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_rename_courses_courses_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(upload_to='author'),
        ),
        migrations.AlterField(
            model_name='courses_upload',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='featured_img'),
        ),
    ]
