# Generated by Django 4.2.5 on 2024-08-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_what_you_learn_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_points', to='Courses.courses_upload'),
        ),
        migrations.AlterField(
            model_name='what_you_learn',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_points', to='Courses.courses_upload'),
        ),
    ]
