# Generated by Django 4.2.5 on 2024-08-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_alter_lesson_course_alter_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='Courses.lesson'),
        ),
    ]
