# Generated by Django 4.2.5 on 2024-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_alter_video_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_upload',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses_upload',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
