# Generated by Django 4.2.5 on 2024-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0016_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
