# Generated by Django 4.2.5 on 2024-08-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0017_course_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_upload',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_Wise_Course', to='Courses.course_category'),
        ),
    ]
