# Generated by Django 4.2.5 on 2024-08-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0018_alter_courses_upload_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teacher_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admin_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_course_name', to='Courses.courses_upload')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
