# Generated by Django 4.2.5 on 2024-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0019_course_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_sales',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
