# Generated by Django 4.2.5 on 2024-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0022_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
