# Generated by Django 4.2.5 on 2024-08-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0023_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='Newsletter_Email',
        ),
    ]
