# Generated by Django 4.2.5 on 2024-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0024_rename_newsletter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_upload',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
